import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ChevronDown, Loader2, ShieldAlert, ShieldCheck, UserRound } from "lucide-react";
import AdminWorkspaceLayout from "./modules/admin/AdminWorkspaceLayout";
import { navigateToPath } from "./lib/appNavigation";
import { apiFetch } from "./lib/api";
import { getConversationIdFromUrl } from "./lib/messagesNavigation";

type Participant = { uid: string; role: string; email: string | null; business_name: string | null; is_suspended: boolean };
type Report = { id: number; reason: string; details: string | null; status: "open" | "reviewed" | "resolved"; reporter_uid: string; reported_uid: string | null; created_at: string; resolution?: string | null; resolved_by_uid?: string | null; resolved_by_email?: string | null; resolved_at?: string | null };
type ThreadData = { conversation: { id:number; listing_id:number|null; event_id:number|null; type:string; created_at:string; last_activity_at:string; buyer:Participant|null; seller:Participant|null; listing:{id:number;name:string;owner_uid:string}|null; event:{id:number;name:string;organizer_uid:string;organizer_name:string}|null; state:"Open"|"Blocked"|"Restricted" }; messages:Array<{id:number;sender_uid:string;body:string;created_at:string}>; reports:Report[]; review:{state:"Unread"|"Reviewed";reviewed_at:string|null}; history:Array<{id:number;admin_uid:string;admin_email:string|null;action_type:string;target_type:string;target_id:string|null;details:any;created_at:string}>; blocked:Array<{blocker_uid:string;blocked_uid:string;reason:string|null;created_at:string}>; restrictions:Array<{restricted_uid:string;reason:string|null;created_by_uid:string;created_at:string}> };

function timeLabel(value?: string | null) { if (!value) return ""; const date = new Date(value); return Number.isNaN(date.getTime()) ? "" : date.toLocaleString(); }

function ParticipantCard({ participant, onView }: { participant: Participant; onView: () => void }) {
  return <div className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-xs font-black uppercase tracking-[0.16em] text-zinc-400">{participant.role}</p><p className="mt-1 truncate text-base font-black text-zinc-900">{participant.business_name || participant.uid}</p><p className="mt-1 text-xs text-zinc-500">{participant.email || "No email on server profile"}</p><p className="mt-2 truncate font-mono text-[10px] text-zinc-400">{participant.uid}</p></div><button type="button" onClick={onView} className="rounded-xl bg-white px-3 py-2 text-xs font-black text-zinc-700 ring-1 ring-zinc-200 hover:bg-zinc-100"><UserRound className="mr-1 inline h-3.5 w-3.5" />View</button></div>{participant.is_suspended ? <span className="mt-3 inline-flex rounded-full bg-red-100 px-2.5 py-1 text-[10px] font-black uppercase tracking-[0.12em] text-red-800">Suspended</span> : null}</div>;
}

export default function AdminMessageThreadPage() {
  const [conversationId] = useState<number | null>(() => getConversationIdFromUrl());
  const [data, setData] = useState<ThreadData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [busyAction, setBusyAction] = useState<string | null>(null);
  const [openMenu, setOpenMenu] = useState<string | null>(null);
  const [viewingParticipant, setViewingParticipant] = useState<Participant | null>(null);
  const [resolution, setResolution] = useState("");

  const load = async () => {
    if (!conversationId || Number.isNaN(conversationId)) { navigateToPath("/admin/messages"); return; }
    setLoading(true); setError(null);
    try {
      const payload = await apiFetch(`/api/admin/messages/${conversationId}`);
      setData(payload as ThreadData);
      await apiFetch(`/api/admin/messages/${conversationId}/review`, { method: "POST" });
    } catch (err:any) { setError(err?.message || "Failed to load conversation."); } finally { setLoading(false); }
  };
  useEffect(() => { void load(); }, [conversationId]);

  const performAction = async (action:string, targetUid?:string, reportId?:number) => {
    if (!conversationId) return;
    setBusyAction(`${action}:${targetUid || reportId || ""}`);
    try {
      await apiFetch(`/api/admin/messages/${conversationId}/action`, { method: "POST", body: JSON.stringify({ action, target_uid: targetUid, report_id: reportId, resolution: resolution.trim() || undefined }) });
      setOpenMenu(null); setResolution(""); await load();
    } catch (err:any) { setError(err?.message || "Moderation action failed."); } finally { setBusyAction(null); }
  };

  const participantByUid = useMemo(() => {
    const map = new Map<string, Participant>();
    if (data?.conversation.buyer) map.set(data.conversation.buyer.uid, data.conversation.buyer);
    if (data?.conversation.seller) map.set(data.conversation.seller.uid, data.conversation.seller);
    return map;
  }, [data]);

  if (loading) return <AdminWorkspaceLayout title="Messages" description="Read-only investigation workspace"><div className="flex min-h-64 items-center justify-center rounded-[1.75rem] border border-zinc-200 bg-white shadow-sm"><Loader2 className="h-6 w-6 animate-spin text-zinc-500" /></div></AdminWorkspaceLayout>;
  if (error || !data || !data.conversation.buyer || !data.conversation.seller) return <AdminWorkspaceLayout title="Messages" description="Read-only investigation workspace"><div className="rounded-[1.75rem] border border-red-200 bg-red-50 p-6 shadow-sm"><p className="text-sm font-semibold text-red-700">{error || "Conversation could not be loaded."}</p><button type="button" onClick={() => navigateToPath("/admin/messages")} className="mt-4 inline-flex items-center gap-2 rounded-2xl bg-zinc-900 px-4 py-2.5 text-sm font-bold text-white"><ArrowLeft className="h-4 w-4" />Back to Messages</button></div></AdminWorkspaceLayout>;

  const { conversation } = data; const otherRole = conversation.event ? "Organizer" : "Seller";
  return <AdminWorkspaceLayout title="Conversation" description="Admin investigation view · read only"><section className="space-y-4">
    <button type="button" onClick={() => navigateToPath("/admin/messages")} className="inline-flex items-center gap-2 rounded-2xl bg-zinc-900 px-4 py-2.5 text-sm font-bold text-white"><ArrowLeft className="h-4 w-4" />Back to Messages</button>
    <div className="rounded-[1.75rem] border border-zinc-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0 flex-1"><p className="text-xs font-black uppercase tracking-[0.18em] text-zinc-400">Conversation #{conversation.id}</p><h2 className="mt-2 truncate text-xl font-black tracking-tight text-zinc-900">{conversation.listing ? conversation.listing.name : conversation.event ? conversation.event.name : "Seller conversation"}</h2><p className="mt-1 text-sm text-zinc-500">{conversation.event ? "Event conversation" : conversation.listing ? "Listing conversation" : "Seller conversation"}</p><div className="mt-3 flex flex-wrap gap-2 text-[11px] font-bold text-zinc-400"><span>Type: {conversation.type}</span><span>Created: {timeLabel(conversation.created_at)}</span><span>Last activity: {timeLabel(conversation.last_activity_at)}</span></div></div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-zinc-100 px-3 py-1.5 text-[11px] font-black uppercase text-zinc-600">Conversation: {conversation.state}</span><span className={`rounded-full px-3 py-1.5 text-[11px] font-black uppercase ${data.review.state === "Reviewed" ? "bg-emerald-100 text-emerald-800" : "bg-amber-100 text-amber-800"}`}>{data.review.state}</span><div className="relative"><button type="button" onClick={() => setOpenMenu(openMenu === "conversation" ? null : "conversation")} className="rounded-xl bg-zinc-900 px-3 py-2 text-xs font-black text-white">Admin Actions <ChevronDown className="ml-1 inline h-3.5 w-3.5" /></button>{openMenu === "conversation" ? <div className="absolute right-0 z-20 mt-2 w-64 rounded-2xl border border-zinc-200 bg-white p-2 shadow-xl"><button type="button" disabled={!!busyAction} onClick={() => void performAction("spam")} className="block w-full rounded-xl px-3 py-2 text-left text-sm font-bold hover:bg-zinc-100">Mark Spam</button>{conversation.state === "Blocked" ? <button type="button" disabled={!!busyAction} onClick={() => void performAction("unblock", conversation.buyer.uid)} className="block w-full rounded-xl px-3 py-2 text-left text-sm font-bold hover:bg-zinc-100">Unblock conversation</button> : null}</div> : null}</div></div></div></div>
    <div className="grid gap-4 lg:grid-cols-2"><ParticipantCard participant={{...conversation.buyer, role:"Buyer"}} onView={() => setViewingParticipant(conversation.buyer)} /><ParticipantCard participant={{...conversation.seller, role:otherRole}} onView={() => setViewingParticipant(conversation.seller)} /></div>
    {conversation.listing ? <div className="rounded-2xl border border-zinc-200 bg-white p-4 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-zinc-400">Related Listing</p><p className="mt-1 font-black text-zinc-900">{conversation.listing.name}</p><p className="mt-1 font-mono text-[10px] text-zinc-400">Listing ID {conversation.listing.id} · Owner {conversation.listing.owner_uid}</p></div> : null}
    {conversation.event ? <div className="rounded-2xl border border-zinc-200 bg-white p-4 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-zinc-400">Related Event</p><p className="mt-1 font-black text-zinc-900">{conversation.event.name}</p><p className="mt-1 font-mono text-[10px] text-zinc-400">Event ID {conversation.event.id} · Organizer {conversation.event.organizer_uid}</p></div> : null}
    {viewingParticipant ? <div className="rounded-2xl border border-blue-200 bg-blue-50 p-4 shadow-sm"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[0.16em] text-blue-700">Participant details</p><p className="mt-1 font-black text-zinc-900">{viewingParticipant.business_name || viewingParticipant.uid}</p><p className="text-sm text-zinc-600">{viewingParticipant.email || "No email"}</p><p className="mt-1 font-mono text-[10px] text-zinc-500">{viewingParticipant.uid}</p></div><button type="button" onClick={() => setViewingParticipant(null)} className="rounded-xl bg-white px-3 py-2 text-xs font-bold text-zinc-700 ring-1 ring-zinc-200">Close</button></div></div> : null}
    {data.reports.length ? <div className="space-y-3">{data.reports.map((report) => <div key={report.id} className="rounded-2xl border border-amber-200 bg-amber-50 p-4 shadow-sm"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="inline-flex items-center gap-1.5 rounded-full bg-amber-100 px-3 py-1 text-[11px] font-black uppercase text-amber-900"><ShieldAlert className="h-3.5 w-3.5" />Reported</span><span className="text-xs font-bold text-zinc-500">Report #{report.id}</span><span className="text-xs font-bold text-zinc-500">{report.status}</span></div><p className="mt-2 font-black text-zinc-900">Reason: {report.reason}</p><p className="mt-1 text-sm text-zinc-600">Reporter: {report.reporter_uid}</p>{report.details ? <p className="mt-2 text-sm text-zinc-700">{report.details}</p> : null}{report.status === "resolved" && report.resolution ? <p className="mt-2 text-sm font-semibold text-emerald-800">Resolution: {report.resolution} · {report.resolved_by_email || report.resolved_by_uid} · {timeLabel(report.resolved_at)}</p> : null}</div>{report.status !== "resolved" ? <div className="flex flex-wrap gap-2 lg:max-w-sm lg:justify-end"><button type="button" disabled={!!busyAction} onClick={() => void performAction("review_report", undefined, report.id)} className="rounded-xl bg-blue-100 px-3 py-2 text-xs font-black text-blue-800">Review</button><input value={resolution} onChange={(e) => setResolution(e.target.value)} placeholder="Resolution / note" className="min-w-[210px] rounded-xl border border-zinc-200 bg-white px-3 py-2 text-xs outline-none" /><button type="button" disabled={!!busyAction} onClick={() => void performAction("resolve_report", undefined, report.id)} className="rounded-xl bg-emerald-100 px-3 py-2 text-xs font-black text-emerald-800">Resolve</button><button type="button" disabled={!!busyAction} onClick={() => void performAction("dismiss_report", undefined, report.id)} className="rounded-xl bg-zinc-200 px-3 py-2 text-xs font-black text-zinc-700">Dismiss</button></div> : null}</div></div>)}</div> : null}
    <div className="overflow-hidden rounded-[1.75rem] border border-zinc-200 bg-zinc-50 shadow-sm"><div className="space-y-5 p-4 sm:p-6">{data.messages.length ? data.messages.map((message) => { const participant = participantByUid.get(message.sender_uid); const isBuyer = message.sender_uid === conversation.buyer.uid; const senderName = participant?.business_name || participant?.uid || message.sender_uid; const senderRole = participant?.role || (isBuyer ? "Buyer" : otherRole); return <div key={message.id} className={`flex ${isBuyer ? "justify-start" : "justify-end"}`}><div className="max-w-[86%] sm:max-w-[72%]"><div className={`mb-1 px-2 font-mono text-[10px] text-zinc-400 ${isBuyer ? "text-left" : "text-right"}`}>{message.sender_uid}</div><div className={`mb-1 px-2 text-[10px] font-black uppercase tracking-[0.14em] text-zinc-400 ${isBuyer ? "text-left" : "text-right"}`}>{senderName} · {senderRole}</div><div className={`rounded-3xl px-4 py-3 text-sm leading-6 ${isBuyer ? "bg-white text-zinc-900 ring-1 ring-zinc-200" : "bg-zinc-900 text-white"}`}><p className="whitespace-pre-wrap break-words">{message.body}</p><p className="mt-2 text-[10px] text-zinc-400">{timeLabel(message.created_at)}</p></div></div></div>; }) : <div className="py-16 text-center text-sm text-zinc-500">No messages in this conversation.</div>}</div><div className="border-t border-zinc-200 bg-white px-4 py-3 text-center text-xs font-semibold text-zinc-400"><ShieldCheck className="mr-1 inline h-3.5 w-3.5" />Admin view · Read only · No message input</div></div>
    <div className="rounded-[1.75rem] border border-zinc-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-zinc-500" /><h3 className="font-black text-zinc-900">Moderation History</h3></div><div className="mt-4 space-y-3">{data.history.length ? data.history.map((entry) => <div key={entry.id} className="flex gap-3"><div className="mt-1 h-2.5 w-2.5 shrink-0 rounded-full bg-zinc-400" /><div><p className="text-sm font-bold text-zinc-800">{entry.action_type.replaceAll("_", " ")}</p><p className="text-xs text-zinc-500">{timeLabel(entry.created_at)} · {entry.admin_email || entry.admin_uid}</p></div></div>) : <p className="text-sm text-zinc-500">No moderation actions recorded yet.</p>}</div></div>
  </section></AdminWorkspaceLayout>;
}
