import { createHash, randomBytes } from "node:crypto";
import type { Request, Response } from "express";
import { getFirebaseAdmin } from "./firebaseAdmin.js";
import { query, withTransaction } from "../postgres.js";

type AuthenticatedValidatorRequestUser = {
  uid: string;
  email: string | null;
  email_verified: boolean;
  is_admin: boolean;
};

type EventCreatorRow = {
  uid: string;
  status: string;
  active_until: string | null;
};

const VALIDATOR_CLIENT = "ticket-validator";
const HANDOFF_TTL_SECONDS = 60;
const HANDOFF_TTL_MS = HANDOFF_TTL_SECONDS * 1000;
let schemaReady = false;

async function ensureValidatorHandoffSchema(): Promise<void> {
  if (schemaReady) return;

  await query(`
    CREATE TABLE IF NOT EXISTS validator_auth_handoffs (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      code_hash TEXT NOT NULL UNIQUE,
      client TEXT NOT NULL,
      uid TEXT NOT NULL,
      expires_at TIMESTAMPTZ NOT NULL,
      consumed_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `);
  await query(`CREATE INDEX IF NOT EXISTS idx_validator_auth_handoffs_lookup ON validator_auth_handoffs (code_hash, client)`);
  await query(`CREATE INDEX IF NOT EXISTS idx_validator_auth_handoffs_expiry ON validator_auth_handoffs (expires_at)`);
  schemaReady = true;
}

function hashHandoffCode(code: string) {
  return createHash("sha256").update(code, "utf8").digest("hex");
}

function createHandoffCode() {
  return randomBytes(32).toString("base64url");
}

async function loadActiveEventCreator(uid: string): Promise<EventCreatorRow | null> {
  const result = await query<EventCreatorRow>(
    "SELECT uid, status, active_until FROM event_creators WHERE uid = $1 LIMIT 1",
    [uid],
  );
  const creator = result.rows[0];
  if (!creator || creator.status !== "approved") return null;
  if (creator.active_until) {
    const activeUntil = new Date(creator.active_until).getTime();
    if (Number.isFinite(activeUntil) && activeUntil < Date.now()) return null;
  }
  return creator;
}

function userRole(customClaims: Record<string, unknown> | undefined) {
  if (customClaims?.admin === true || customClaims?.role === "admin") return "admin";
  return "validator";
}

export async function validatorHandoffHandler(req: Request, res: Response) {
  const user = req.user as AuthenticatedValidatorRequestUser | undefined;
  if (!user) return res.status(401).json({ error: "Authentication required" });

  if (!(await loadActiveEventCreator(user.uid))) {
    return res.status(403).json({ error: "Approved event creator access is required" });
  }

  try {
    await ensureValidatorHandoffSchema();
    const code = createHandoffCode();
    const codeHash = hashHandoffCode(code);
    const expiresAt = new Date(Date.now() + HANDOFF_TTL_MS).toISOString();

    await query(
      `DELETE FROM validator_auth_handoffs
       WHERE expires_at <= CURRENT_TIMESTAMP
          OR (consumed_at IS NOT NULL AND consumed_at <= CURRENT_TIMESTAMP - INTERVAL '1 hour')`,
    );

    await query(
      `INSERT INTO validator_auth_handoffs (code_hash, client, uid, expires_at)
       VALUES ($1, $2, $3, $4)`,
      [codeHash, VALIDATOR_CLIENT, user.uid, expiresAt],
    );

    return res.json({ success: true, code, expiresInSeconds: HANDOFF_TTL_SECONDS });
  } catch (error) {
    console.error("Failed to create Ticket Validator auth handoff:", error);
    return res.status(500).json({ error: "Unable to create Ticket Validator sign-in handoff" });
  }
}

export async function validatorHandoffExchangeHandler(req: Request, res: Response) {
  const code = typeof req.body?.code === "string" ? req.body.code.trim() : "";
  if (!code || code.length > 256) {
    return res.status(400).json({ error: "A valid Ticket Validator handoff code is required" });
  }

  try {
    await ensureValidatorHandoffSchema();
    const codeHash = hashHandoffCode(code);

    const handoff = await withTransaction(async (client) => {
      await client.query(
        `DELETE FROM validator_auth_handoffs
         WHERE expires_at <= CURRENT_TIMESTAMP
            OR (consumed_at IS NOT NULL AND consumed_at <= CURRENT_TIMESTAMP - INTERVAL '1 hour')`,
      );

      const result = await client.query<{ id: number; uid: string }>(
        `SELECT id, uid
         FROM validator_auth_handoffs
         WHERE code_hash = $1
           AND client = $2
           AND consumed_at IS NULL
           AND expires_at > CURRENT_TIMESTAMP
         LIMIT 1
         FOR UPDATE`,
        [codeHash, VALIDATOR_CLIENT],
      );

      const row = result.rows[0];
      if (!row) return undefined;

      const consumed = await client.query(
        `UPDATE validator_auth_handoffs
         SET consumed_at = CURRENT_TIMESTAMP
         WHERE id = $1
           AND consumed_at IS NULL
           AND expires_at > CURRENT_TIMESTAMP`,
        [row.id],
      );

      return (consumed.rowCount ?? 0) === 1 ? row : undefined;
    });

    if (!handoff) {
      return res.status(401).json({ error: "Invalid, expired, or already-used Ticket Validator handoff" });
    }

    if (!(await loadActiveEventCreator(handoff.uid))) {
      return res.status(403).json({ error: "Approved event creator access is required" });
    }

    try {
      const firebaseAdmin = getFirebaseAdmin();
      const firebaseUser = await firebaseAdmin.auth().getUser(handoff.uid);
      const customToken = await firebaseAdmin.auth().createCustomToken(handoff.uid, {
        client: VALIDATOR_CLIENT,
        role: userRole(firebaseUser.customClaims as Record<string, unknown> | undefined),
      });
      return res.json({ success: true, customToken });
    } catch (error) {
      console.error("Failed to create Ticket Validator session token from handoff:", error);
      return res.status(500).json({ error: "Unable to create Ticket Validator session" });
    }
  } catch (error) {
    console.error("Failed to redeem Ticket Validator auth handoff:", error);
    return res.status(500).json({ error: "Unable to redeem Ticket Validator sign-in handoff" });
  }
}
